### ISSUE TITLE
一处Repo更名提醒

### ISSUE THREAD

**Issue by SkipM4** [project-mirai/awesome-mirai#53]
[Itsusinn/MessageForward](https://github.com/Itsusinn/message-forward/tree/main/message-source/mirai-source ) 支持不同IM平台的消息转发，如Minecraft,QQ,Discord
项目已被重命名为[mesagisto](https://github.com/MeowCat-Studio/mesagisto)
Mirai插件[地址](https://github.com/MeowCat-Studio/mirai-mesaga-fonto)

**Comment by Karlatemp** [comment]
会在源 repo 所有者 @Itsusinn 确认后修改
